IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'teams')
BEGIN
    CREATE TABLE teams (
        id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        name NVARCHAR(255) NOT NULL UNIQUE,
        description NVARCHAR(MAX) NOT NULL DEFAULT '',
        daily_token_cap BIGINT NOT NULL DEFAULT 999999999,
        created_at DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
        created_by UNIQUEIDENTIFIER NULL REFERENCES users(id)
    );
END
